-- MySQL Script generated by MySQL Workbench
-- Tue 19 Nov 2019 11:58:46 AM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema easy-apply
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema easy-apply
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `easy-apply` DEFAULT CHARACTER SET utf8 ;
USE `easy-apply` ;

-- -----------------------------------------------------
-- Table `easy-apply`.`Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easy-apply`.`Company` ;

CREATE TABLE IF NOT EXISTS `easy-apply`.`Company` (
  `company_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `industry` VARCHAR(45) NOT NULL,
  `website` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`company_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easy-apply`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easy-apply`.`User` ;

CREATE TABLE IF NOT EXISTS `easy-apply`.`User` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easy-apply`.`Vacancy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easy-apply`.`Vacancy` ;

CREATE TABLE IF NOT EXISTS `easy-apply`.`Vacancy` (
  `vacancy_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`vacancy_id`),
  INDEX `company_id_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `company_id`
    FOREIGN KEY (`company_id`)
    REFERENCES `easy-apply`.`Company` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easy-apply`.`Application`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easy-apply`.`Application` ;

CREATE TABLE IF NOT EXISTS `easy-apply`.`Application` (
  `application_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `vacancy_id` INT NOT NULL,
  PRIMARY KEY (`application_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `vacancy_id_idx` (`vacancy_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `easy-apply`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `vacancy_id`
    FOREIGN KEY (`vacancy_id`)
    REFERENCES `easy-apply`.`Vacancy` (`vacancy_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
